<a href="https://colab.research.google.com/github/gaurav-26-11/COVID-19-Risk-Identifier-ML-Model/blob/main/mini_project_FINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from pandas import DataFrame
from random import randint
import random
lst_tmp = []
lst_oxy = []
lst_hrt = []

for i in range(0, 1000):
    
    tmp = randint(96,105)
    oxy = randint(85,99)
    hrt = randint(60,130)


    lst_tmp.append(tmp)
    lst_oxy.append(oxy)
    lst_hrt.append(hrt)
    
random.shuffle(lst_tmp)
random.shuffle(lst_oxy)
random.shuffle(lst_hrt)      
print(lst_tmp)
print(lst_oxy)
print(lst_hrt)


[97, 104, 104, 96, 98, 99, 98, 96, 96, 96, 102, 96, 102, 99, 103, 105, 98, 99, 105, 96, 103, 98, 102, 101, 99, 101, 96, 104, 97, 100, 96, 99, 96, 98, 97, 102, 96, 96, 100, 103, 103, 99, 99, 104, 97, 103, 103, 99, 100, 105, 97, 102, 98, 96, 105, 104, 104, 97, 100, 96, 105, 101, 97, 104, 98, 103, 96, 102, 100, 96, 98, 100, 101, 104, 100, 96, 97, 97, 104, 105, 104, 96, 105, 99, 99, 96, 97, 103, 104, 101, 104, 103, 100, 96, 97, 100, 102, 104, 98, 98, 101, 100, 102, 102, 98, 103, 105, 104, 101, 102, 102, 99, 101, 96, 101, 103, 103, 102, 96, 103, 98, 100, 96, 97, 101, 96, 100, 100, 105, 104, 100, 100, 104, 99, 101, 104, 104, 97, 102, 100, 96, 96, 98, 105, 98, 103, 102, 103, 105, 97, 98, 103, 103, 102, 97, 96, 105, 100, 96, 103, 101, 103, 105, 103, 102, 99, 102, 102, 102, 104, 103, 100, 100, 97, 103, 103, 102, 99, 104, 105, 98, 104, 99, 100, 102, 104, 99, 98, 105, 99, 102, 104, 105, 103, 96, 96, 105, 103, 99, 102, 97, 96, 104, 100, 99, 102, 98, 99, 100, 103, 102, 105, 100, 105, 104, 99, 105, 

In [ ]:
import numpy

x = lst_tmp
y = lst_oxy
z = lst_hrt
A = numpy.array((x, y, z), dtype=float)
A

array([[ 97., 104., 104., ..., 101.,  97., 102.],
       [ 96.,  90.,  89., ...,  93.,  87.,  93.],
       [118., 122.,  63., ..., 109.,  92., 128.]])

In [ ]:
AT= A.T   #transposing the matrix presentation using numpy
print(AT)

[[ 97.  96. 118.]
 [104.  90. 122.]
 [104.  89.  63.]
 ...
 [101.  93. 109.]
 [ 97.  87.  92.]
 [102.  93. 128.]]


In [ ]:
df = DataFrame (AT,columns = ['temp','oxygen','heart beat'])
df

temp  oxygen  heart beat
0     97.0    96.0       118.0
1    104.0    90.0       122.0
2    104.0    89.0        63.0
3     96.0    86.0       107.0
4     98.0    91.0        92.0
..     ...     ...         ...
995  101.0    98.0       116.0
996  105.0    85.0       114.0
997  101.0    93.0       109.0
998   97.0    87.0        92.0
999  102.0    93.0       128.0

[1000 rows x 3 columns]

In [ ]:
i=0
j=0
k=0
counter=0 
output=[]
while counter < 1000:
  if lst_tmp[i]>int(99):
    if lst_oxy[j]<int(90):
      output.append("possible risk")  
      #break
    else:
      if lst_hrt[k]>int(90):
        output.append("no possible risk")  
        #break
      else:
        output.append("possible risk")
        #break
  else:
    if lst_oxy[j]<int(90):
      if lst_hrt[k]>int(90):
        output.append("possible risk")  
        #break
      else:
        output.append("need further investigation") 
        #break
    else:
      if lst_hrt[k]>int(90):
        output.append("no possible risk")
        #break
      else:
        output.append("no possible risk")
        #break
  i+=1
  j+=1
  k+=1
  counter+=1

In [ ]:
print(output)

['no possible risk', 'no possible risk', 'possible risk', 'possible risk', 'no possible risk', 'need further investigation', 'no possible risk', 'no possible risk', 'need further investigation', 'possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'need further investigation', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'possible risk', 'no possible risk', 'possible risk', 'need further investigation', 'possible risk', 'possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'need further investigation', 'no possible risk', 'possible risk', 'no possible risk', 'possible risk', 'possible risk', 'possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'no

In [ ]:
df1 = DataFrame (output,columns = ['pridiction'])
df1

pridiction
0    no possible risk
1    no possible risk
2       possible risk
3       possible risk
4    no possible risk
..                ...
995  no possible risk
996     possible risk
997  no possible risk
998     possible risk
999  no possible risk

[1000 rows x 1 columns]

In [ ]:
import pandas as pd
result = pd.concat([df, df1], axis=1)
result

temp  oxygen  heart beat        pridiction
0     97.0    96.0       118.0  no possible risk
1    104.0    90.0       122.0  no possible risk
2    104.0    89.0        63.0     possible risk
3     96.0    86.0       107.0     possible risk
4     98.0    91.0        92.0  no possible risk
..     ...     ...         ...               ...
995  101.0    98.0       116.0  no possible risk
996  105.0    85.0       114.0     possible risk
997  101.0    93.0       109.0  no possible risk
998   97.0    87.0        92.0     possible risk
999  102.0    93.0       128.0  no possible risk

[1000 rows x 4 columns]

In [ ]:
result.to_csv("result1.csv")

#MACHINE LEARNING MODEL 

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [ ]:
df=pd.read_csv("result1_final_csv.csv")
df

Unnamed: 0  temp  oxygen  heart beat                  prediction
0             0   105      99         109            no possible risk
1             1   100      89          95               possible risk
2             2    99      93         123            no possible risk
3             3   103      89          96               possible risk
4             4   104      96          67            no possible risk
..          ...   ...     ...         ...                         ...
995         995    99      87          77  need further investigation
996         996   104      87          90               possible risk
997         997   100      93          62            no possible risk
998         998    96      89         106               possible risk
999         999   100      85         125               possible risk

[1000 rows x 5 columns]

In [ ]:
y=df["prediction"]  #yaha se kya ho raha h?

In [ ]:
X=df.drop("prediction",axis=1)

In [ ]:
X=X.drop("Unnamed: 0",axis=1)

In [ ]:
X.head()

temp  oxygen  heart beat
0   105      99         109
1   100      89          95
2    99      93         123
3   103      89          96
4   104      96          67

In [ ]:
X.describe()

temp       oxygen   heart beat
count  1000.000000  1000.000000  1000.000000
mean    100.450000    91.651000    94.583000
std       2.928494     4.233571    20.675846
min      96.000000    85.000000    60.000000
25%      98.000000    88.000000    77.000000
50%     100.000000    91.000000    93.000000
75%     103.000000    95.000000   112.000000
max     105.000000    99.000000   130.000000

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42,stratify=y) #splitting

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

#KNN


In [ ]:
from sklearn.neighbors import KNeighborsClassifier  #training

In [ ]:
model=KNeighborsClassifier(n_neighbors=2)

In [ ]:
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [ ]:
model.score(X_test,y_test)

0.9633333333333334

#KNN prediction

In [ ]:
data=pd.DataFrame({0:[96],1:[99],2:[72]})

In [ ]:
data=scaler.transform(data)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
model.predict(data)

array(['no possible risk'], dtype=object)

logistic regression 

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
model.score(X_test,y_test)

0.9233333333333333

In [ ]:
data=pd.DataFrame({0:[96],1:[99],2:[72]})  #manual feed
data=scaler.transform(data)
model.predict(data)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"


array(['no possible risk'], dtype=object)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
