<a href="https://colab.research.google.com/github/gaurav-26-11/COVID-19-Risk-Identifier-ML-Model/blob/main/mini_project_FINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from pandas import DataFrame
from random import randint
import random
lst_tmp = []
lst_oxy = []
lst_hrt = []

#Generating DATASET for ML model training using random library functions
for i in range(0, 1000):
    
    tmp = randint(96,105)
    oxy = randint(85,99)
    hrt = randint(60,130)


    lst_tmp.append(tmp)
    lst_oxy.append(oxy)
    lst_hrt.append(hrt)
    
random.shuffle(lst_tmp)
random.shuffle(lst_oxy)
random.shuffle(lst_hrt)      
print(lst_tmp)
print(lst_oxy)
print(lst_hrt)


[99, 99, 104, 96, 104, 104, 98, 99, 98, 100, 102, 98, 96, 104, 97, 101, 104, 103, 102, 96, 102, 101, 99, 98, 105, 101, 96, 102, 100, 102, 100, 97, 101, 100, 96, 105, 100, 104, 102, 104, 105, 98, 105, 100, 96, 101, 102, 96, 100, 104, 101, 99, 97, 97, 101, 104, 101, 104, 105, 97, 104, 105, 103, 99, 97, 102, 102, 96, 103, 105, 100, 102, 104, 104, 98, 104, 97, 99, 104, 97, 105, 104, 98, 100, 98, 98, 99, 97, 97, 102, 97, 102, 103, 99, 104, 100, 98, 96, 104, 105, 102, 96, 98, 100, 98, 96, 99, 99, 99, 99, 102, 100, 104, 105, 96, 103, 102, 102, 103, 99, 99, 97, 105, 105, 96, 96, 101, 101, 102, 104, 102, 102, 100, 99, 101, 104, 99, 101, 98, 96, 98, 98, 102, 96, 103, 105, 99, 105, 97, 102, 99, 100, 105, 100, 104, 102, 96, 100, 100, 96, 102, 102, 104, 96, 100, 98, 103, 97, 104, 104, 104, 97, 98, 105, 105, 100, 104, 105, 104, 99, 104, 104, 105, 98, 97, 100, 105, 100, 104, 98, 102, 98, 105, 97, 96, 101, 99, 99, 96, 101, 104, 97, 100, 101, 105, 101, 105, 97, 105, 103, 103, 102, 103, 101, 102, 102, 1

In [2]:
#Creating Dataframe (basically a table)
import numpy

x = lst_tmp
y = lst_oxy
z = lst_hrt
A = numpy.array((x, y, z), dtype=float)
A

array([[ 99.,  99., 104., ...,  97., 105.,  96.],
       [ 96.,  98.,  88., ...,  90.,  93.,  97.],
       [113., 126.,  62., ...,  88., 130.,  65.]])

In [3]:
AT= A.T   #transposing the matrix presentation using numpy
print(AT)

[[ 99.  96. 113.]
 [ 99.  98. 126.]
 [104.  88.  62.]
 ...
 [ 97.  90.  88.]
 [105.  93. 130.]
 [ 96.  97.  65.]]


In [4]:
df = DataFrame (AT,columns = ['temp','oxygen','heart beat'])
df

temp  oxygen  heart beat
0     99.0    96.0       113.0
1     99.0    98.0       126.0
2    104.0    88.0        62.0
3     96.0    99.0       108.0
4    104.0    98.0       104.0
..     ...     ...         ...
995  102.0    86.0        91.0
996   97.0    98.0        92.0
997   97.0    90.0        88.0
998  105.0    93.0       130.0
999   96.0    97.0        65.0

[1000 rows x 3 columns]

In [5]:
#Risk Determination code as per the truth table.
i=0
j=0
k=0
counter=0 
output=[]
while counter < 1000:
  if lst_tmp[i]>int(99):
    if lst_oxy[j]<int(90):
      output.append("possible risk")  
      #break
    else:
      if lst_hrt[k]>int(90):
        output.append("no possible risk")  
        #break
      else:
        output.append("possible risk")
        #break
  else:
    if lst_oxy[j]<int(90):
      if lst_hrt[k]>int(90):
        output.append("possible risk")  
        #break
      else:
        output.append("need further investigation") 
        #break
    else:
      if lst_hrt[k]>int(90):
        output.append("no possible risk")
        #break
      else:
        output.append("no possible risk")
        #break
  i+=1
  j+=1
  k+=1
  counter+=1

In [6]:
print(output)

['no possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'possible risk', 'possible risk', 'need further investigation', 'possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'possible risk', 'need further investigation', 'possible risk', 'possible risk', 'possible risk', 'no possible risk', 'possible risk', 'possible risk', 'possible risk', 'no possible risk', 'possible risk', 'possible risk', 'possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'possible risk', 'possible risk', 'no possible risk', 'possible risk', 'no possible risk', 'no possible risk', 'no possible risk', 'no possible r

In [7]:
df1 = DataFrame (output,columns = ['prediction'])
df1

prediction
0    no possible risk
1    no possible risk
2       possible risk
3    no possible risk
4    no possible risk
..                ...
995     possible risk
996  no possible risk
997  no possible risk
998  no possible risk
999  no possible risk

[1000 rows x 1 columns]

In [9]:
#concatinating the two tables.
import pandas as pd
result = pd.concat([df, df1], axis=1)
result

temp  oxygen  heart beat        prediction
0     99.0    96.0       113.0  no possible risk
1     99.0    98.0       126.0  no possible risk
2    104.0    88.0        62.0     possible risk
3     96.0    99.0       108.0  no possible risk
4    104.0    98.0       104.0  no possible risk
..     ...     ...         ...               ...
995  102.0    86.0        91.0     possible risk
996   97.0    98.0        92.0  no possible risk
997   97.0    90.0        88.0  no possible risk
998  105.0    93.0       130.0  no possible risk
999   96.0    97.0        65.0  no possible risk

[1000 rows x 4 columns]

In [10]:
#Exporting the table into a .csv file
result.to_csv("result1.csv")

#MACHINE LEARNING MODEL 

In [11]:
#Importing required libraries for the KNN and Logistic Regression.
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [13]:
df=pd.read_csv("result1_final_csv.csv")
df

Unnamed: 0  temp  oxygen  heart beat                  prediction
0             0   105      99         109            no possible risk
1             1   100      89          95               possible risk
2             2    99      93         123            no possible risk
3             3   103      89          96               possible risk
4             4   104      96          67            no possible risk
..          ...   ...     ...         ...                         ...
995         995    99      87          77  need further investigation
996         996   104      87          90               possible risk
997         997   100      93          62            no possible risk
998         998    96      89         106               possible risk
999         999   100      85         125               possible risk

[1000 rows x 5 columns]

In [15]:
y=df["prediction"]

In [17]:
X=df.drop("prediction",axis=1) #dropping last column

In [18]:
X=X.drop("Unnamed: 0",axis=1) #dropping missing value entries

In [19]:
X.head()

temp  oxygen  heart beat
0   105      99         109
1   100      89          95
2    99      93         123
3   103      89          96
4   104      96          67

In [20]:
X.describe()

temp       oxygen   heart beat
count  1000.000000  1000.000000  1000.000000
mean    100.450000    91.651000    94.583000
std       2.928494     4.233571    20.675846
min      96.000000    85.000000    60.000000
25%      98.000000    88.000000    77.000000
50%     100.000000    91.000000    93.000000
75%     103.000000    95.000000   112.000000
max     105.000000    99.000000   130.000000

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
#splitting on size 0.3 for test 0.7 for train.
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42,stratify=y) 

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

#KNN


In [26]:
from sklearn.neighbors import KNeighborsClassifier  #training

In [27]:
model=KNeighborsClassifier(n_neighbors=2)

In [28]:
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [29]:
model.score(X_test,y_test)

0.9633333333333334

#KNN prediction

In [30]:
data=pd.DataFrame({0:[96],1:[99],2:[72]})

In [31]:
data=scaler.transform(data)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"


In [32]:
model.predict(data)

array(['no possible risk'], dtype=object)

logistic regression 

In [33]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [34]:
model.score(X_test,y_test)

0.9233333333333333

In [35]:
data=pd.DataFrame({0:[96],1:[99],2:[72]})  #manual feed
data=scaler.transform(data)
model.predict(data)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  "X does not have valid feature names, but"


array(['no possible risk'], dtype=object)